### ISSUE TITLE
Wrong type field in mysql.cpp

### ISSUE THREAD

**Issue by rodrigotabsan** [akay25/mysqlIO#1]
In mysql_result_query function you return wrong values (you return 0 instead of "")... It should be:

String mysql_result_query(String query, String field){
  String res = "";
  String q = "query=" + query + "&field=" + field;
  Serial.println(q);
  res = Serial.readString();
  if(res == "-")
  return "";
  while(res.length() <= 0){
  res = Serial.readString();  
  if(res == "-")
  return "";
  }
  return res;
}

**Comment by akay25** [comment]
I just checked it and want to apologise for the terrible setup.
If possible can you please create pull request and I will merge it.

Thanks.

**Comment by rodrigotabsan** [comment]
Hi! I have not write access... could you give me write access please?
Thank you.

**Comment by akay25** [comment]
I mean, create a fork and make a pull request.

**Comment by rodrigotabsan** [comment]
it is done :)
